version: "3.8"

services:
  frontend:
    build: .
    container_name: demirayhidrolik-frontend
    ports:
      - "3003:80"   # nginx -> container
    restart: unless-stopped
    environment:
      VITE_API_URL: https://api.demirayhidrolik.com
