services:
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    container_name: react-ecommerce
    restart: unless-stopped
    networks:
      backend_network: {}

networks:
  backend_network:
    external: true
    name: e-trader-backend_ecommerce-network
