services:
  ecommerce-app:
    build:
      context: .
    ports:
      - "81:80"
    container_name: react-ecommerce
    restart: unless-stopped
    environment:
      VITE_API_URL: /api
    networks:
      backend_network: {}

networks:
  backend_network:
    external: true
    name: e-trader-backend_ecommerce-network
