services:
  ecommerce-app:
    build:
      context: .
    ports:
      - "80:80" # Sadece bu kalsÄ±n! 8080'i sildik.
    container_name: react-ecommerce
    restart: unless-stopped
    networks:
      backend_network: {}

networks:
  backend_network:
    external: true
    name: e-trader-backend_ecommerce-network
