version: "3.8"

services:
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Dışarıdan 80, içeriden Nginx'in dinlediği 80
    container_name: react-ecommerce
    restart: unless-stopped
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
