version: "3.8"

services:
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"     # Ana site için
      - "8080:8080" # React kodundaki API isteklerini yakalamak için
    container_name: react-ecommerce
    restart: unless-stopped
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true # Backend ile aynı networkü kullanması için
